name: build

on:
  workflow_dispatch:
    inputs:
      triggerIssueId:
        description: 'issueId'
        required: false
      customParam:
        description: 'customParam'
        required: false
      ghevent:
        description: 'ghevent'
        required: false

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      packages: write
      issues: write
      pull-requests: write
      actions: write

    steps:
    - name: Set up JDK
      id: setup-java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - uses: oras-project/setup-oras@v1
      with:
        version: 1.0.0

    - name: build
      env:
        GHEVENT: ${{ github.event.inputs.ghevent }}
        GH_TOKEN: ${{ github.token }}
        CURRENT_GHEVENT: ${{ github.event }}
      run: |
        oras pull -uyunhorn -p${{ secrets.GITHUB_TOKEN }} ghcr.io/yunhorn/files:build
        chmod +x build.sh
        ./build.sh
