name: sync

on:
  workflow_dispatch:
  push:

permissions: write-all

jobs:

  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      packages: write
    strategy:
      fail-fast: false 
      matrix:
        img: 
        - docker.io/eclipse-temurin
        - docker.io/cruizba/ubuntu-dind
        - docker.io/docker
        - docker.io/redis 
        - docker.io/mysql
        - docker.io/valkey/valkey
        - registry.k8s.io/etcd
        - docker.io/apachepulsar/pulsar
        - docker.io/victoriametrics/vmagent
        - docker.io/jaegertracing/all-in-one
        - docker.io/prom/prometheus
        - docker.io/victoriametrics/victoria-metrics
        - docker.io/oliver006/redis_exporter
        - docker.io/kindest/node
        - docker.io/eclipse-mosquitto
        - apache/bookkeeper
        - docker.io/ubuntu 
        - docker.io/debain
        - docker.io/openeuler/openeuler
    steps:

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: $GITHUB_REPOSITORY_OWNER
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: sync
      run: |
        #skopeo sync --dest-authfile $HOME/.docker/config.json --src docker --dest docker ${{ matrix.img }} ghcr.io/$GITHUB_REPOSITORY_OWNER
        docker run -v $HOME/.docker/config.json:/tmp/config.json --rm quay.io/skopeo/stable sync --dest-authfile /tmp/config.json  --src docker --dest docker ${{ matrix.img }} ghcr.io/$GITHUB_REPOSITORY_OWNER


