name: build

on:
  workflow_dispatch:
  push:

permissions: write-all

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: $GITHUB_REPOSITORY_OWNER
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: sync
      run: |
        skopeo copy --dest-authfile $HOME/.docker/config.json  --src docker --dest docker docker.io/eclipse-temurin ghcr.io/$GITHUB_REPOSITORY_OWNER
